services:
  - type: web
    name: trendscope-service
    env: docker
    plan: free
    region: oregon
    branch: main
    rootDir: .
    dockerfilePath: Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: sqlite
